name: Angular Frontend CI

on:
  workflow_dispatch:

jobs:
  angular-sonar:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app (production)
        run: npm run build -- --configuration=production

      - name: Run SonarQube scan
        run: |
          sudo docker run --rm \
            -e SONAR_HOST_URL="http://192.168.79.128:9000" \
            -e SONAR_TOKEN="sqa_6b79d9e85ab7e2eea7f917872766b9e6af8bd6c0" \
            -v "$PWD:/usr/src" \
            sonarsource/sonar-scanner-cli \
            -Dsonar.projectKey=espritDevHubFrontEnd \
            -Dsonar.sources=/usr/src/src \
            -Dsonar.exclusions="**/*.spec.ts,**/node_modules/**" \
            -Dsonar.projectBaseDir=/usr/src \
            -Dsonar.host.url=http://192.168.79.128:9000 \
            -Dsonar.login=sqa_6b79d9e85ab7e2eea7f917872766b9e6af8bd6c0

      - name: Build Docker image
        run: |
          sudo docker build -t jobrane23/esprit-frontend:latest .

      - name: Push Docker image
        run: |
          sudo docker login -u jobrane23 -p PI23381121
          sudo docker push jobrane23/esprit-frontend:latest
